//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Tas.Core.Api
{
    #pragma warning disable // Disable all warnings

    /// <summary>a class of principal (typically a human) identifiable by SSO. In theory developer-defined but for now only TAS can create.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum PrincipalType
    {
        [System.Runtime.Serialization.EnumMember(Value = "user")]
        User = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "candidate")]
        Candidate = 1,
    
    }
    
    /// <summary>A set of SAML values that uniquely identify this person, consistently across TAS apps, and with any number of potential IdPs</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SamlSubject 
    {
        /// <summary>principal type</summary>
        [Newtonsoft.Json.JsonProperty("pt", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PrincipalType Pt { get; set; }
    
        /// <summary>key of the SAML assertion with the the TAS core SAML database</summary>
        [Newtonsoft.Json.JsonProperty("samlKey", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string SamlKey { get; set; }
    
        [Newtonsoft.Json.JsonProperty("nameID", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string NameID { get; set; }
    
        [Newtonsoft.Json.JsonProperty("entityID", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string EntityID { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static SamlSubject FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SamlSubject>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Api 
    {
        [Newtonsoft.Json.JsonProperty("developer", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Developer { get; set; }
    
        [Newtonsoft.Json.JsonProperty("uriTemplate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string UriTemplate { get; set; }
    
        /// <summary>the principal type of this API (not present if this is not an on-behalf API)</summary>
        [Newtonsoft.Json.JsonProperty("principalType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public PrincipalType? PrincipalType { get; set; }
    
        /// <summary>link to a RAML document describing this API (if any)</summary>
        [Newtonsoft.Json.JsonProperty("raml", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Raml { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static Api FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Api>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
}