//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Tas.Core.App
{
    #pragma warning disable // Disable all warnings

    /// <summary>details about a specific app</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class App 
    {
        /// <summary>the app's principal type. Not present if the app does not use SSO</summary>
        [Newtonsoft.Json.JsonProperty("principalType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PrincipalType { get; set; }
    
        /// <summary>the secret key used by the proxy to encrypt the principal cookie. Not present if the app does not use SSO</summary>
        [Newtonsoft.Json.JsonProperty("principalCookieSecretKey", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PrincipalCookieSecretKey { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static App FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<App>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
}