//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Tas.Core.PasswordManagerCapabilities
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class PasswordManagerCapabilities 
    {
        /// <summary>true if this account manager can create accounts - in which case TAS SSO will display a sign up button</summary>
        [Newtonsoft.Json.JsonProperty("canCreateAccounts", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool CanCreateAccounts { get; set; }
    
        /// <summary>A link to the terms and conditions that the user must agree to before creating an account. Only present if canCerateAccounts is true.</summary>
        [Newtonsoft.Json.JsonProperty("createAccountTermsAndConditionsUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CreateAccountTermsAndConditionsUrl { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static PasswordManagerCapabilities FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PasswordManagerCapabilities>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
}