//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Tas.Core.RebootStatus
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class TenantEvent 
    {
        [Newtonsoft.Json.JsonProperty("kind", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public TenantEventKind Kind { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static TenantEvent FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<TenantEvent>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class AppEvent 
    {
        [Newtonsoft.Json.JsonProperty("kind", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public AppEventKind Kind { get; set; }
    
        [Newtonsoft.Json.JsonProperty("app", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string App { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static AppEvent FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<AppEvent>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class TenantStatusEvent 
    {
        [Newtonsoft.Json.JsonProperty("kind", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public TenantStatusEventKind Kind { get; set; }
    
        [Newtonsoft.Json.JsonProperty("incarnation", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Incarnation { get; set; }
    
        [Newtonsoft.Json.JsonProperty("securityGeneration", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int SecurityGeneration { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static TenantStatusEvent FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<TenantStatusEvent>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class OrderedEvent 
    {
        [Newtonsoft.Json.JsonProperty("seq", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Seq { get; set; }
    
        [Newtonsoft.Json.JsonProperty("time", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTime Time { get; set; }
    
        [Newtonsoft.Json.JsonProperty("event", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public TenantEvent Event { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static OrderedEvent FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<OrderedEvent>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RebootStatus 
    {
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RebootStatusStatus Status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("latestEvent", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? LatestEvent { get; set; }
    
        /// <summary>the URI that the browser should redirect the user to once this reboot is complete, possibly at a new storefront if a patch set apply swapped out the current one</summary>
        [Newtonsoft.Json.JsonProperty("continuePage", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ContinuePage { get; set; }
    
        [Newtonsoft.Json.JsonProperty("events", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.ObjectModel.ObservableCollection<OrderedEvent> Events { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static RebootStatus FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RebootStatus>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum TenantEventKind
    {
        [System.Runtime.Serialization.EnumMember(Value = "patchSetApplyRebootStart")]
        PatchSetApplyRebootStart = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "bumpSecurityGenerationRebootStart")]
        BumpSecurityGenerationRebootStart = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "simpleRebootStart")]
        SimpleRebootStart = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantPreHaltStart")]
        TenantPreHaltStart = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantPreHaltComplete")]
        TenantPreHaltComplete = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantHaltStart")]
        TenantHaltStart = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantHaltComplete")]
        TenantHaltComplete = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPatchesApplyStart")]
        AppPatchesApplyStart = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPatchesApplyComplete")]
        AppPatchesApplyComplete = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "bumpSecurityGenerationComplete")]
        BumpSecurityGenerationComplete = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantPreStartStart")]
        TenantPreStartStart = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantPreStartComplete")]
        TenantPreStartComplete = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantStartStart")]
        TenantStartStart = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = "tenantStartComplete")]
        TenantStartComplete = 13,
    
        [System.Runtime.Serialization.EnumMember(Value = "patchSetApplyRebootComplete")]
        PatchSetApplyRebootComplete = 14,
    
        [System.Runtime.Serialization.EnumMember(Value = "bumpSecurityGenerationRebootComplete")]
        BumpSecurityGenerationRebootComplete = 15,
    
        [System.Runtime.Serialization.EnumMember(Value = "simpleRebootComplete")]
        SimpleRebootComplete = 16,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum AppEventKind
    {
        [System.Runtime.Serialization.EnumMember(Value = "appPreHaltStart")]
        AppPreHaltStart = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreHaltError")]
        AppPreHaltError = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreHaltTimeout")]
        AppPreHaltTimeout = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreHaltComplete")]
        AppPreHaltComplete = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "appHaltStart")]
        AppHaltStart = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "appHaltError")]
        AppHaltError = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "appHaltTimeout")]
        AppHaltTimeout = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "appHaltComplete")]
        AppHaltComplete = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreStartStart")]
        AppPreStartStart = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreStartError")]
        AppPreStartError = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreStartTimeout")]
        AppPreStartTimeout = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = "appPreStartComplete")]
        AppPreStartComplete = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = "appStartStart")]
        AppStartStart = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = "appStartError")]
        AppStartError = 13,
    
        [System.Runtime.Serialization.EnumMember(Value = "appStartTimeout")]
        AppStartTimeout = 14,
    
        [System.Runtime.Serialization.EnumMember(Value = "appStartComplete")]
        AppStartComplete = 15,
    
        [System.Runtime.Serialization.EnumMember(Value = "appInstallStart")]
        AppInstallStart = 16,
    
        [System.Runtime.Serialization.EnumMember(Value = "appInstallError")]
        AppInstallError = 17,
    
        [System.Runtime.Serialization.EnumMember(Value = "appInstallTimeout")]
        AppInstallTimeout = 18,
    
        [System.Runtime.Serialization.EnumMember(Value = "appInstallComplete")]
        AppInstallComplete = 19,
    
        [System.Runtime.Serialization.EnumMember(Value = "appUninstallStart")]
        AppUninstallStart = 20,
    
        [System.Runtime.Serialization.EnumMember(Value = "appUninstallError")]
        AppUninstallError = 21,
    
        [System.Runtime.Serialization.EnumMember(Value = "appUninstallTimeout")]
        AppUninstallTimeout = 22,
    
        [System.Runtime.Serialization.EnumMember(Value = "appUninstallComplete")]
        AppUninstallComplete = 23,
    
        [System.Runtime.Serialization.EnumMember(Value = "appEditComplete")]
        AppEditComplete = 24,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum TenantStatusEventKind
    {
        [System.Runtime.Serialization.EnumMember(Value = "tenantStatusEvent")]
        TenantStatusEvent = 0,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum RebootStatusStatus
    {
        [System.Runtime.Serialization.EnumMember(Value = "notLaunched")]
        NotLaunched = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "inProcess")]
        InProcess = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "complete")]
        Complete = 2,
    
    }
}