//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace Tas.Tenant.CandidateWorkflow
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class Bucket 
    {
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Id { get; set; }
    
        [Newtonsoft.Json.JsonProperty("label", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Label { get; set; }
    
        /// <summary>Buckets have a phase, which represents the approximate part of the recruitment process this bucket is for - for example the phase 'interview' might have several buckets (e.g. 'line manager interview', etc.).</summary>
        [Newtonsoft.Json.JsonProperty("phase", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public BucketPhase Phase { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static Bucket FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Bucket>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class CandidateWorkflow 
    {
        [Newtonsoft.Json.JsonProperty("label", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Label { get; set; }
    
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Id { get; set; }
    
        [Newtonsoft.Json.JsonProperty("buckets", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.ObjectModel.ObservableCollection<int> Buckets { get; set; } = new System.Collections.ObjectModel.ObservableCollection<int>();
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
        
        public static CandidateWorkflow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<CandidateWorkflow>(data, new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter() });
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.10.27.0 (Newtonsoft.Json v9.0.0.0)")]
    public enum BucketPhase
    {
        [System.Runtime.Serialization.EnumMember(Value = "new")]
        New = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "screening")]
        Screening = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "interview")]
        Interview = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "selection")]
        Selection = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "offer")]
        Offer = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "approval")]
        Approval = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "hire")]
        Hire = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "onboard")]
        Onboard = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "decline")]
        Decline = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "other")]
        Other = 9,
    
    }
}